
const specialities = [
  { id: 1, label: ['Valeologist','Валеолог'] },
  { id: 2, label: ['Venereologist','Венеролог'] },
  { id: 3, label: ['Virologist','Вирусолог'] },
  { id: 4, label: ['Gastroenterologist','Гастроэнтеролог'] },
  { id: 5, label: ['Hematologist','Гематолог'] },
  { id: 6, label: ['Geneticist','Генетик'] },
  { id: 7, label: ['Geriatrician','Гериатр'] },
  { id: 8, label: ['Gynecologist','Гинеколог'] },
  { id: 9, label: ['Homeopathist','Гомеопат'] },
  { id: 10, label: ['Dermatologist','Дерматолог'] },
  { id: 11, label: ['Diagnostician','Диагност'] },
  { id: 12, label: ['Nutritionist','Диетолог'] },
  { id: 13, label: ['Dental','Зубной'] },
  { id: 14, label: ['Immunologist','Иммунолог'] },
  { id: 15, label: ['Cardiologist','Инфекционист'] },
  { id: 16, label: ['Cardiologist','Кардиолог'] },
  { id: 17, label: ['Cardiac Surgeon','Кардиохирург'] },
  { id: 18, label: ['Cosmetologist','Косметолог'] },
  { id: 19, label: ['Speech therapist','Логопед'] },
  { id: 20, label: ['Chiropractor','Мануальный терапевт'] },
  { id: 21, label: ['Nurse','Медицинская сестра'] },
  { id: 22, label: ['Expert in narcology','Нарколог'] },
  { id: 23, label: ['Neurologist','Невролог'] },
  { id: 24, label: ['Neuropathologist','Невропатолог'] },
  { id: 25, label: ['Neurosurgeon','Нейрохирург'] },
  { id: 26, label: ['Ophthalmologist','Окулист'] },
  { id: 27, label: ['Oncologist','Онколог'] },
  { id: 28, label: ['Orthodontist','Ортодонт'] },
  { id: 29, label: ['Orthopedist','Ортопед'] },
  { id: 30, label: ['Otolaryngologist','Отоларинголог'] },
  { id: 31, label: ['Ophthalmologist','Офтальмолог'] },
  { id: 32, label: ['Pathologist','Патологоанатом'] },
  { id: 33, label: ['Pediatrician','Педиатр'] },
  { id: 34, label: ['Plastic Surgeon','Пластический хирург'] },
  { id: 35, label: ['Proctologist','Проктолог'] },
  { id: 36, label: ['Psychiatrist','Психиатр'] },
  { id: 37, label: ['Psychologist','Психолог'] },
  { id: 38, label: ['Psychotherapist','Психотерапевт'] },
  { id: 39, label: ['Resuscitator','Реаниматолог'] },
  { id: 40, label: ['Rheumatologist','Ревматолог'] },
  { id: 41, label: ['Sexopathologist','Сексопатолог'] },
  { id: 42, label: ['Family','Семейный'] },
  { id: 43, label: ['Emergency','Скорой помощи'] },
  { id: 44, label: ['Сo-founder','Сомнолог'] },
  { id: 45, label: ['Dentist','Стоматолог'] },
  { id: 46, label: ['Surdologist','Сурдолог'] },
  { id: 47, label: ['Therapist','Терапевт'] },
  { id: 48, label: ['Toxicologist','Токсиколог'] },
  { id: 49, label: ['Traumatologist','Травматолог'] },
  { id: 50, label: ['Transplantologist','Трансплантолог'] },
  { id: 51, label: ['Urologist','Уролог'] },
  { id: 52, label: ['Pharmacist','Фармацевт'] },
  { id: 53, label: ['Physiotherapist','Физиотерапевт'] },
  { id: 54, label: ['Surgeon','Хирург'] },
  { id: 55, label: ['Endocrinologist','Эндокринолог'] }
]


module.exports = {
  specialities,
}